### ISSUE TITLE
abaqus-python-addpkg

### ISSUE THREAD

**Issue by tmhphd** [nasa/CompDam_DGD#18]
Conda environment does not seem to still have access to old enough version of scipy for python 2.7.3 and numpy 1.6.2. See the following error when using abaqus-python-addpkg.py.

conda create -n abq_2018 python=2.7.3 pip numpy=1.6.2 scipy
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - numpy=1.6.2
  - python=2.7.3

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Traceback (most recent call last):
  File "abaqus-python-addpkg.py", line 492, in <module>
    args.func(args)
  File "abaqus-python-addpkg.py", line 366, in _install
    subprocess.check_call(cmd, shell=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conda create -n abq_2018 python=2.7.3 pip numpy=1.6.2 scipy' returned non-zero exit status 1.

I have tried the following with no success:
1. updated the abaqus-python-addpkg code to search conda-forge with no success
2. tried to find wheels of the correct version. Finding a version compatible (scipy 0.16) with numpy 1.6.2 results in the following error in python "ImportError: numpy openblaspy flavour needed."

**Comment by acbergan** [comment]
Hmm, I guess you are using windows? It should work for windows. I have not tested this code on linux or mac. I tried the command you list and it works for me on windows. Have you set `conda config --set restore_free_channel true`? See https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/free-channel.html

**Comment by tmhphd** [comment]
Dear acbergan,
That was it. I tried this but guess I did something wrong when setting up the conda config and went through thinking it was correct. Thanks for your help.

**Comment by Dragon1998a** [comment]
Hi, Could you help me out with this script? I keep getting this error:
![image](https://github.com/nasa/CompDam_DGD/assets/83971800/08442324-e570-42bd-9537-2889859d4679)
