### ISSUE TITLE
abaqus-python-addpkg

### ISSUE THREAD

**Issue by Dragon1998a** [nasa/CompDam_DGD#21]
I can't seem to get the script to work. so far I have tried:
abaqus-python-addpkg.py install --conda scipy
abaqus-python-addpkg.py --abaqus-cmd abq2023 install --conda scipy
"abaqus-python-addpkg.py -v install scipy"
"abaqus-python-addpkg.py install --help"

all tries returned the same error:
![image](https://github.com/nasa/CompDam_DGD/assets/83971800/109da7b7-c56e-4a80-8ac2-9cab5bd86786)

**Comment by acbergan** [comment]
Please take a look at the documentation:
https://github.com/nasa/CompDam_DGD/tree/master/utilities/abaqus-python-addpkg

Your commands do not follow the required order/format.
